# Generated by Django 3.0.8 on 2020-09-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_attempt',
            field=models.DateTimeField(null=True),
        ),
    ]
