# Generated by Django 3.0.8 on 2020-10-19 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(db_index=True, default=0)),
                ('no_of_hints_used', models.IntegerField(default=0)),
                ('no_of_attempts', models.IntegerField(default=0)),
                ('question_id', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(null=True)),
                ('xp', models.IntegerField(default=0)),
                ('hint_used', models.BooleanField(default=False)),
                ('hint_powerup', models.BooleanField(default=False)),
                ('skip_powerup', models.BooleanField(default=False)),
                ('accept_close_answer', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
