# Generated by Django 3.0.8 on 2020-09-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rank',
        ),
        migrations.AddField(
            model_name='userstatus',
            name='point_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
