# Generated by Django 3.0.8 on 2020-11-21 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_logging'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOutreach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outreach', models.CharField(choices=[('Instagram', 'Instagram'), ('Twitter', 'Twitter'), ('Facebook', 'Facebook'), ('Word of mouth', 'Word of mouth'), ('Website', 'Website'), ('Whatsapp', 'Whatsapp')], max_length=13)),
                ('is_college_student', models.BooleanField()),
                ('year', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
