# Generated by Django 3.0.8 on 2020-09-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200924_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='last_answered_ts',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
