# Generated by Django 3.0.8 on 2020-11-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_useroutreach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroutreach',
            name='outreach',
            field=models.CharField(choices=[('Instagram', 'Instagram'), ('Twitter', 'Twitter'), ('Facebook', 'Facebook'), ('Word of mouth', 'Word of mouth'), ('WhatsApp', 'WhatsApp'), ('Reddit', 'Reddit'), ('E-Mail', 'E-Mail'), ('Other', 'Other')], max_length=13),
        ),
        migrations.AlterField(
            model_name='useroutreach',
            name='year',
            field=models.IntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)]),
        ),
    ]
