# Generated by Django 3.0.8 on 2020-09-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200924_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='first_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
