# Generated by Django 3.0.8 on 2020-11-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_outreach_year_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroutreach',
            name='year',
            field=models.IntegerField(blank=True, choices=[(2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], null=True),
        ),
    ]
