# Generated by Django 3.0.8 on 2020-12-04 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_null_outreach_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='xp',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
