# Generated by Django 3.0.8 on 2020-12-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_min_max_to_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='logging',
            name='answer',
            field=models.CharField(default='', max_length=255),
        ),
    ]
