# Generated by Django 3.0.8 on 2020-11-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='solves',
            field=models.IntegerField(default=0),
        ),
    ]
